import { Card, Categories } from 'components/molecules';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { Footer, Header } from 'components/organisms';
import FilterIcon from 'assets/icons/filter.svg';
import { useApp } from 'context/AppContext';

const Home: NextPage = () => {
  const { listings } = useApp();
  const [categoryId, setCategoryId] = useState(1);

  return (
    <div className="h-screen overflow-hidden flex flex-col">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="flex px-20 pt-5">
        <Categories
          onClick={(categoryId) => setCategoryId(categoryId)}
          categoryId={categoryId}
        />
        <div className="flex items-center h-12 border-solid border-[1px] border-[#DDDDDD] rounded-xl px-4 ml-6">
          <FilterIcon />
          Filters
        </div>
      </div>
      <div className="grid grid-cols-5 gap-x-6 gap-y-10 mt-5 px-20 overflow-auto">
        {listings
          .find((e) => e.id === categoryId)
          ?.data.map((e) => (
            <Card key={e.id} categoryId={categoryId} {...e} />
          ))}
      </div>
      <Footer />
    </div>
  );
};

export default Home;
